/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * exportDHCP.java
 *
 * Created on 23/07/2011, 15:43:27
 */
package ipfixed;

import Engine.CrearXML;
import Modelo.Host;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author matuuar
 */
public class exportDHCP extends javax.swing.JDialog {

    /** Creates new form exportDHCP */
    public exportDHCP(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mostrarRuta = new javax.swing.JTextField();
        seleccionarArchivosExport = new javax.swing.JButton();
        aceptarExportDHCP = new javax.swing.JButton();
        carcelarExportDHCP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mostrarRuta.setToolTipText("Ruta del archivo seleccionado");
        mostrarRuta.setEnabled(false);
        mostrarRuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarRutaMouseClicked(evt);
            }
        });

        seleccionarArchivosExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipfixed/resources/16.png"))); // NOI18N
        seleccionarArchivosExport.setText("Seleccionar...");
        seleccionarArchivosExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarArchivosExportActionPerformed(evt);
            }
        });

        aceptarExportDHCP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipfixed/resources/8.png"))); // NOI18N
        aceptarExportDHCP.setText("Exportar");
        aceptarExportDHCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarExportDHCPActionPerformed(evt);
            }
        });

        carcelarExportDHCP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipfixed/resources/116.png"))); // NOI18N
        carcelarExportDHCP.setText("Carcelar");
        carcelarExportDHCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carcelarExportDHCPActionPerformed(evt);
            }
        });

        jTextPane1.setBorder(null);
        jTextPane1.setEditable(false);
        jScrollPane1.setViewportView(jTextPane1);
        jTextPane1.setText("Este dialogo le permite exportar su configuración a un archivo de texto plano que podrá incluir en su configuración del servicio DHCP utilizando la opción \"include [ruta/al/archivo]\".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(mostrarRuta, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seleccionarArchivosExport, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(carcelarExportDHCP, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aceptarExportDHCP, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mostrarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccionarArchivosExport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carcelarExportDHCP)
                    .addComponent(aceptarExportDHCP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarArchivosExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarArchivosExportActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showSaveDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            fileSave = fileChooser.getSelectedFile();
            mostrarRuta.setText(fileSave.getAbsolutePath());
        }
    }//GEN-LAST:event_seleccionarArchivosExportActionPerformed

    private void aceptarExportDHCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarExportDHCPActionPerformed
        if (fileSave != null) {
            ArrayList<Host> h = Main.getHost();
            String out = "#Archivo de configuración creado con IPFixed\n";
            for (int i = 0; i < h.size(); i++) {
                out += h.get(i).toString();
            }
            try {
                if (!fileSave.exists()) {
                    fileSave.createNewFile();
                }
                fileSave.setWritable(true);
                FileWriter fw = new FileWriter(fileSave);
                fw.write(out);
                fw.flush();
                fw.close();
                JOptionPane.showMessageDialog(rootPane, "Archivo guardado."
                    , "Guardado", JOptionPane.INFORMATION_MESSAGE);
                dispose();

            } catch (IOException ex) {
                Logger.getLogger(exportDHCP.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Error al guardar. Intenta nuevamente"
                    , "Error al guardar", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un donde guardar primero.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aceptarExportDHCPActionPerformed

    private void mostrarRutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarRutaMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showSaveDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            fileSave = fileChooser.getSelectedFile();
            mostrarRuta.setText(fileSave.getAbsolutePath());
        }


    }//GEN-LAST:event_mostrarRutaMouseClicked

    private void carcelarExportDHCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carcelarExportDHCPActionPerformed
        dispose();
    }//GEN-LAST:event_carcelarExportDHCPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                exportDHCP dialog = new exportDHCP(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarExportDHCP;
    private javax.swing.JButton carcelarExportDHCP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField mostrarRuta;
    private javax.swing.JButton seleccionarArchivosExport;
    // End of variables declaration//GEN-END:variables
    File fileSave;
}
