/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * exportarItalc.java
 *
 * Created on 25/07/2011, 10:55:45
 */
package ipfixed;

import Modelo.Host;
import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jdom.DocType;
import org.jdom.Document;
import org.jdom.Element;
import org.jdom.output.XMLOutputter;

/**
 *
 * @author matuuar
 */
public class exportarItalc extends javax.swing.JDialog {

    /** Creates new form exportarItalc */
    public exportarItalc(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        versionItalc = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        nombreClase = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        exportarItalc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setText("Version");
        jPanel1.add(jLabel1);

        versionItalc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1.0.9", "1.0.13" }));
        jPanel1.add(versionItalc);

        jLabel2.setText("Nombre de la Clase:");
        jPanel1.add(jLabel2);
        jPanel1.add(nombreClase);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipfixed/resources/116.png"))); // NOI18N
        jButton1.setText("Carcelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        exportarItalc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipfixed/resources/8.png"))); // NOI18N
        exportarItalc.setText("Exportar");
        exportarItalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarItalcActionPerformed(evt);
            }
        });
        jPanel1.add(exportarItalc);

        jTextPane1.setEditable(false);
        jScrollPane1.setViewportView(jTextPane1);
        jTextPane1.setText("Esta opción le permite crear un archivo de configuración para el gestor de clases iTalc. Indique la versión y el nombre de la clase, y se creará un archivo .xml para utilizarlo en iTalc.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exportarItalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarItalcActionPerformed
        if (nombreClase.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre de clase.");

        } else {
            ArrayList<Host> h = Main.getHost();
            if (h.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay hosts a exportar.");
            } else {
                /*Pedimos ubicación del archivo a guardar */
                JFileChooser fileChooser = new JFileChooser();
                int seleccion = fileChooser.showSaveDialog(this);
                if (seleccion == JFileChooser.APPROVE_OPTION) {
                    File file = fileChooser.getSelectedFile();
                    /* Creamos el documentos xml con la estructura esperada
                     * por Italc
                     */
                    Element root = new Element("globalclientconfig");
                    root.setAttribute("version", versionItalc.getSelectedItem().toString());
                    Element body = new Element("body");
                    Element classroom = new Element("classroom");
                    classroom.setAttribute("name", nombreClase.getText());
                    for (int i = 0; i < h.size(); i++) {
                        Element client = new Element("client");
                        //<client hostname="172.16.6.1" mac="" type="0" id="1313" name="CEP387-01"/>
                        client.setAttribute("hostname", h.get(i).getIp());
                        client.setAttribute("mac", h.get(i).getMacCon2Puntos());
                        client.setAttribute("type", "0");
                        client.setAttribute("id", Integer.toString(h.get(i).getId()));
                        client.setAttribute("name", h.get(i).getNombre());
                        classroom.addContent(client);
                    }
                    body.addContent(classroom);
                    root.addContent(body);
                    Document doc = new Document(root);//Creamos el documento
                    doc.setDocType(new DocType("italc-config-file"));
                    try {
                        XMLOutputter out = new XMLOutputter();
                        FileOutputStream salida = new FileOutputStream(file);
                        out.output(doc, salida);
                        salida.flush();
                        salida.close();
                        out.output(doc, System.out);
                    } catch (Exception e) {
                    }
                    //System.out.print(doc.toString());
                JOptionPane.showMessageDialog(this, "Exportación finalizada.\nEl archivo generado debe ser ubicado en \nla carpeta de configuración de iTalc.\nEn linux: '$HOME_USER/.italc' ", "Archivo generado", JOptionPane.INFORMATION_MESSAGE);
                dispose();
                }
            }
        }
    }//GEN-LAST:event_exportarItalcActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                exportarItalc dialog = new exportarItalc(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exportarItalc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField nombreClase;
    private javax.swing.JComboBox versionItalc;
    // End of variables declaration//GEN-END:variables
}
